spring.application.name=db_crud_api_spring

spring.datasource.url=jdbc:postgresql://localhost:5432/db_crud_api_spring
spring.datasource.username=postgres
spring.datasource.password=07052007
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

