spring.application.name=security_spring

spring.datasource.url=jdbc:postgresql://localhost:5432/db_spring_security
spring.datasource.username=postgres
spring.datasource.password=07052007
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=0f3d9b8c5f1a2e7d4c8b6a9e1f5d7c3b8a1e6d9f2c4b7a8e5f1d3c9b6a2e7f4c8d1b5e9e3f7c2d6b8a
jwt.expiration=86400000