spring.application.name=ass_users_brands

spring.datasource.url=jdbc:postgresql://localhost:5432/db_ass_user_brand
spring.datasource.username=postgres
spring.datasource.password=07052007
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect